### ISSUE TITLE
Remove line from text display

### ISSUE THREAD

**Issue by joshcwinton** [joshcwinton/SHRDLUOnline#30]
As new responses are rendered, a thin line occasionally appears in the list

**Comment by joshcwinton** [comment]
<img width="268" alt="Screen Shot 2021-03-06 at 9 22 25 PM" src="https://user-images.githubusercontent.com/29495809/110227036-0e15d880-7ec2-11eb-83cb-6ee6cb6be038.png">

**Comment by JasperCheung** [comment]
@joshcwinton this can be closed with changes in #38 right?

**Comment by joshcwinton** [comment]
@JasperCheung yeah, you can double-check but I haven't seen it at all since then
