### ISSUE TITLE
Add env variables for url name

### ISSUE THREAD

**Issue by JasperCheung** [joshcwinton/SHRDLUOnline#68]
We want to use localhost when we develop and use heroku when we deploy. Add env vars.

This is good enough: https://medium.com/@ysteven.chen2/how-to-deploy-your-react-app-on-heroku-and-create-your-environment-variables-8bc8e2ca7f78.

**Comment by joshcwinton** [comment]
@JasperCheung this is finished right?

**Comment by JasperCheung** [comment]
@joshcwinton yep

**Comment by joshcwinton** [comment]
💯
